#!/usr/bin/env ruby

require "hiser"
require 'optparse'

ARGV << '-h' if ARGV.empty?  # sets help screen as default
options = {}
OptionParser.new do |opts|
  opts.program_name = 'Hiser'
  #opts.on('-g', '--generate', 'Generate a hiser project') { options[:generate] = true }
  opts.on('-s', '--serialize', 'Create serialized files from hiera data') { options[:serialize] = true }
  opts.on('-h', '--help', 'Show help') { puts opts; exit }
  opts.version = Hiser::VERSION
  opts.parse!
end

if options[:generate]
  Hiser::Cli.generate
elsif options[:serialize]
  Hiser::Cli.start
end
